name: Build and Push to Yandex Container Registry

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Авторизуемся в Yandex Container Registry
      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v3
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      # 3. Собираем Docker-образ и пушим его в облако
      - name: Build and Push Docker Image
        env:
          CR_REGISTRY: ${{ secrets.YC_REGISTRY_ID }}
          CR_REPOSITORY: simple-app
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Сборка
          docker build -t $CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .
          docker build -t $CR_REGISTRY/$CR_REPOSITORY:latest .

          # Пуш в реестр
          docker push $CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG
          docker push $CR_REGISTRY/$CR_REPOSITORY:latest
